SET SERVEROUTPUT ON

--visualizar_lista_depart

DECLARE
V_CUR GEST_DEPART.TCURSOR;
V_DEPT_NO DEPART.DEPT_NO%TYPE;
V_DNOMBRE DEPART.DNOMBRE%TYPE;
V_LOC DEPART.LOC%TYPE;
BEGIN
  GEST_DEPART.VISUALIZAR_LISTA_DEPART(V_CUR);
  LOOP
    FETCH V_CUR INTO V_DEPT_NO,V_DNOMBRE,V_LOC;
    EXIT WHEN V_CUR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(V_DEPT_NO||' '||V_DNOMBRE);
  END LOOP;
END;

--visualizar_datos_depart SIN CUROSR

DECLARE 
P_DEPT_NO DEPART.DEPT_NO%TYPE:=20;
P_DNOMBRE DEPART.DNOMBRE%TYPE;
P_LOC DEPART.LOC%TYPE;
P_NUM_EMPLEADOS NUMBER;
BEGIN
  GEST_DEPART.VISUALIZAR_DATOS_DEPART
  (P_DEPT_NO,P_DNOMBRE,P_LOC,P_NUM_EMPLEADOS);
  DBMS_OUTPUT.PUT_LINE
  (P_DEPT_NO||' '||P_DNOMBRE||' '||P_LOC||' '||P_NUM_EMPLEADOS);
END;

--visualizar_datos_depart CON CUROSR
DECLARE 
P_DNOMBRE DEPART.DNOMBRE%TYPE:='VENTAS';
P_CURSOR_LISTA GEST_DEPART.TCURSOR;
P_NUM_EMPLEADOS NUMBER;
V_LOC DEPART.LOC%TYPE;
V_DEPT_NO DEPART.DEPT_NO%TYPE;
V_DNOMBRE DEPART.DNOMBRE%TYPE;
BEGIN
  GEST_DEPART.VISUALIZAR_DATOS_DEPART
  (P_DNOMBRE,P_CURSOR_LISTA,P_NUM_EMPLEADOS);
  LOOP
  FETCH P_CURSOR_LISTA INTO V_DEPT_NO,V_DNOMBRE,V_LOC;
  EXIT WHEN P_CURSOR_LISTA%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE
  (V_DEPT_NO||' '||V_DNOMBRE||' '||V_LOC||' '||P_NUM_EMPLEADOS);
  END LOOP;
END;