CREATE OR REPLACE PACKAGE BODY GEST_DEPART IS
/*-------------------------------------------*/
FUNCTION BUSCAR_DEPART_POR_NOMBRE
(P_DNOMBRE DEPART.DNOMBRE%TYPE)
RETURN DEPART.DEPT_NO%TYPE 
IS
V_DEPT_NO DEPART.DEPT_NO%TYPE;
BEGIN 
  SELECT DEPT_NO INTO V_DEPT_NO 
  FROM DEPART
  WHERE UPPER(DNOMBRE)=UPPER(P_DNOMBRE);
  RETURN V_DEPT_NO;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
  V_DEPT_NO:=NULL;
  RETURN V_DEPT_NO;
END BUSCAR_DEPART_POR_NOMBRE;
/*-------------------------------------------*/
PROCEDURE INSERTAR_DEPART 
(P_DNOMBRE DEPART.DNOMBRE%TYPE,P_LOC DEPART.LOC%TYPE)
IS
V_MAX_DEPT_NO DEPART.DEPT_NO%TYPE;
V_DNOMBRE DEPART.DNOMBRE%TYPE;
BEGIN 
  SELECT MAX(DEPT_NO) INTO V_MAX_DEPT_NO 
  FROM DEPART;
  SELECT DNOMBRE INTO V_DNOMBRE 
  FROM DEPART 
  WHERE UPPER(DNOMBRE)=P_DNOMBRE;
  IF SQL%NOTFOUND
  THEN
    INSERT INTO DEPART VALUES
    (V_MAX_DEPT_NO+10,P_DNOMBRE,P_LOC);
  END IF;
END INSERTAR_DEPART;
/*-------------------------------------------*/
PROCEDURE BORRAR_DEPART 
(P1_DEPT_NO DEPART.DEPT_NO%TYPE,
P2_DEPT_NO DEPART.DEPT_NO%TYPE)
IS
BORRAR_DEPT_NO DEPART.DEPT_NO%TYPE;
NUEVO_DEPT_NO DEPART.DEPT_NO%TYPE;
E_DELETE EXCEPTION;
BEGIN 
  SELECT DEPT_NO INTO BORRAR_DEPT_NO
  FROM DEPART 
  WHERE DEPT_NO=P1_DEPT_NO;
  SELECT DEPT_NO INTO NUEVO_DEPT_NO
  FROM DEPART 
  WHERE DEPT_NO=P2_DEPT_NO;     
  UPDATE EMPLE SET DEPT_NO=P2_DEPT_NO
  WHERE DEPT_NO=BORRAR_DEPT_NO;
  IF SQL%FOUND THEN
    DELETE 
    FROM DEPART
    WHERE DEPT_NO=BORRAR_DEPT_NO;
    IF SQL%FOUND THEN
      COMMIT;
    ELSE
      ROLLBACK;
      RAISE E_DELETE;
    END IF;
  END IF;
  EXCEPTION
  WHEN E_DELETE THEN
    RAISE_APPLICATION_ERROR
    (-20051,'ERROR AL BORRAR EL DEPARTAMENTO');
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR
    (-20011,'ERR COD. DEPARTAMENTO NO ENCONTRADO');
  WHEN TOO_MANY_ROWS THEN
    RAISE_APPLICATION_ERROR
    (-20001,'ERR COD. DEPARTAMENTO DUPLICADO');
END BORRAR_DEPART;
/*-------------------------------------------*/
PROCEDURE CAMBIAR_LOCALIDAD
(P_DEPT_NO DEPART.DEPT_NO%TYPE,P_LOC IN DEPART.LOC%TYPE)
IS
VIEJO_DEPART DEPART.DEPT_NO%TYPE;
ERROR_DESCONOCIDO EXCEPTION;
BEGIN 
  SELECT DEPT_NO INTO VIEJO_DEPART 
  FROM DEPART 
  WHERE DEPT_NO=P_DEPT_NO;
  UPDATE DEPART
  SET LOC=P_LOC
  WHERE DEPT_NO=P_DEPT_NO;
  IF SQL%NOTFOUND THEN 
    RAISE ERROR_DESCONOCIDO;
  END IF;
  EXCEPTION 
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR
    (-20011,'ERR COD. DEPARTAMENTO NO ENCONTRADO');
  WHEN TOO_MANY_ROWS THEN
    RAISE_APPLICATION_ERROR
    (-20001,'ERR COD. DEPARTAMENTO DUPLICADO');
  WHEN ERROR_DESCONOCIDO THEN
    RAISE_APPLICATION_ERROR
    (-20999,'ERROR DESCONOCIDO');

END CAMBIAR_LOCALIDAD;
/*-------------------------------------------*/
PROCEDURE VISUALIZAR_LISTA_DEPART
(P_CURSOR_LISTA OUT TCURSOR)/*TCURSOR CREADO POR MI O */
IS                              /*SYS_REFCURSOR*/
BEGIN
OPEN P_CURSOR_LISTA FOR
SELECT DEPT_NO,DNOMBRE,LOC FROM DEPART;
END VISUALIZAR_LISTA_DEPART;
/*PARA PROBAR EJECUTAR 
"ejecutar_procedure_lista_paquete.sql"*/
/*-------------------------------------------*/
PROCEDURE VISUALIZAR_DATOS_DEPART             
(P_DEPT_NO IN OUT DEPART.DEPT_NO%TYPE,
 P_DNOMBRE OUT DEPART.DNOMBRE%TYPE,
 P_LOC OUT DEPART.LOC%TYPE,
 P_NUM_EMPLEADOS OUT NUMBER)
IS
V_DEPT_NO DEPART.DEPT_NO%TYPE; 
BEGIN
  SELECT DEPT_NO INTO V_DEPT_NO
  FROM DEPART
  WHERE DEPT_NO=P_DEPT_NO;  
  SELECT DEPT_NO,DNOMBRE,LOC 
  INTO P_DEPT_NO,P_DNOMBRE,P_LOC
  FROM DEPART
  WHERE DEPT_NO=V_DEPT_NO;  
  SELECT NVL(COUNT(EMP_NO),0) INTO P_NUM_EMPLEADOS
  FROM EMPLE
  WHERE DEPT_NO=V_DEPT_NO
  GROUP BY DEPT_NO;
  
EXCEPTION 
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR
    (-20011,'ERR COD. DEPARTAMENTO NO ENCONTRADO');
  WHEN TOO_MANY_ROWS THEN
    RAISE_APPLICATION_ERROR
    (-20001,'ERR COD. DEPARTAMENTO DUPLICADO');
END VISUALIZAR_DATOS_DEPART;
/*-------------------------------------------*/
PROCEDURE VISUALIZAR_DATOS_DEPART
(P_DNOMBRE DEPART.DNOMBRE%TYPE,
 P_CURSOR_LISTA OUT TCURSOR,
 P_NUM_EMPLEADOS OUT NUMBER)
  IS
V_DEPT_NO DEPART.DEPT_NO%TYPE;
ERROR_NO_ENCONTRADO EXCEPTION;
 BEGIN
	V_DEPT_NO:=BUSCAR_DEPART_POR_NOMBRE(P_NOMBRE);
	IF V_DEPT_NO IS NOT NULL
	THEN
  OPEN P_CURSOR_LISTA FOR
  SELECT DEPT_NO,DNOMBRE,LOC  
  FROM DEPART
  WHERE DEPT_NO=V_DEPT_NO;
  SELECT NVL(COUNT(EMP_NO),0) INTO P_NUM_EMPLEADOS
  FROM EMPLE
  WHERE DEPT_NO=V_DEPT_NO
  GROUP BY DEPT_NO;
	ELSE 
		RAISE ERROR_NO_ENCONTRADO;
	END IF;
EXCEPTION 
WHEN ERROR_NO_ENCONTRADO THEN 
  (-20011,'ERR COD. DEPARTAMENTO NO ENCONTRADO');
END VISUALIZAR_DATOS_DEPART;
/*-------------------------------------------*/
END GEST_DEPART;
