CREATE OR REPLACE PACKAGE BODY GEST_DEPART IS

FUNCTION BUSCAR_DEPART_POR_NOMBRE
(P_DNOMBRE DEPART.DNOMBRE%TYPE)
RETURN DEPART.DEPT_NO%TYPE 
IS
V_DEPT_NO DEPART.DEPT_NO%TYPE;
BEGIN 
  SELECT DEPT_NO INTO V_DEPT_NO 
  FROM DEPART
  WHERE UPPER(DNOMBRE)=UPPER(P_DNOMBRE);
  RETURN V_DEPT_NO;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
  V_DEPT_NO:=NULL;
  RETURN V_DEPT_NO;
END BUSCAR_DEPART_POR_NOMBRE;

PROCEDURE INSERTAR_DEPART 
(P_DNOMBRE DEPART.DNOMBRE%TYPE,P_LOC DEPART.LOC%TYPE)
IS
V_MAX_DEPT_NO DEPART.DEPT_NO%TYPE;
V_DNOMBRE DEPART.DNOMBRE%TYPE;
BEGIN 
  SELECT MAX(DEPT_NO) INTO V_MAX_DEPT_NO FROM DEPART;
  SELECT DNOMBRE INTO V_DNOMBRE FROM DEPART WHERE UPPER(DNOMBRE)=P_DNOMBRE;
  IF SQL%NOTFOUND
  THEN
    INSERT INTO DEPART VALUES
    (V_MAX_DEPT_NO+10,P_DNOMBRE,P_LOC);
  END IF;
END INSERTAR_DEPART;

PROCEDURE BORRAR_DEPART 
(P1_DEPT_NO DEPART.DEPT_NO%TYPE,P2_DEPT_NO DEPART.DEPT_NO%TYPE)
IS
BORRAR_DEPT_NO DEPART.DEPT_NO%TYPE;
CURSOR C1 IS 
SELECT EMP_NO FROM EMPLE
WHERE DEPT_NO=BORRAR_DEPT_NO;
EMPLE  C1%ROWTYPE ;
BEGIN 
  SELECT DEPT_NO INTO BORRAR_DEPT_NO
  FROM DEPART 
  WHERE DEPT_NO=P1_DEPT_NO;
  IF SQL%FOUND THEN
    OPEN  C1;
    FETCH C1 Into EMPLE;
    WHILE C1%FOUND LOOP
      UPDATE EMPLE SET DEPT_NO=P2_DEPT_NO
      WHERE DEPT_NO=BORRAR_DEPT_NO;
    FETCH C1 Into EMPLE;
    END LOOP;
    CLOSE C1;
  END IF;
  DELETE 
  FROM DEPART
  WHERE DEPT_NO=BORRAR_DEPT_NO;
END BORRAR_DEPART;

PROCEDURE CAMBIAR_LOCALIDAD
(P_DEPT_NO DEPART.DEPT_NO%TYPE,P_LOC IN DEPART.LOC%TYPE)
IS
BEGIN 
  UPDATE DEPART
  SET LOC=P_LOC
  WHERE DEPT_NO=P_DEPT_NO;
END CAMBIAR_LOCALIDAD;
END GEST_DEPART;


