REM ******** TABLA DEPART: *********** 

DROP TABLE DEPART CASCADE CONSTRAINTS; 

CREATE TABLE DEPART (
 	DEPT_NO  NUMBER(2),
	DNOMBRE  VARCHAR2(14), 
 	LOC      VARCHAR2(14),
	CONSTRAINT DEP_PK PRIMARY KEY (DEPT_NO)
	);

INSERT INTO DEPART VALUES (10,'CONTABILIDAD','SEVILLA');
INSERT INTO DEPART VALUES (20,'INVESTIGACION','MADRID');
INSERT INTO DEPART VALUES (30,'VENTAS','BARCELONA');
INSERT INTO DEPART VALUES (40,'PRODUCCION','BILBAO');

COMMIT;

REM /*  ******** TABLA EMPLE: ************* */

DROP TABLE EMPLE CASCADE CONSTRAINTS; 

CREATE TABLE EMPLE (
 	EMP_NO    NUMBER(4),
 	APELLIDO  VARCHAR2(10),
 	OFICIO    VARCHAR2(15),
 	ID_JEFE  NUMBER(4) ,
 	FECHA_ALTA DATE,
 	SALARIO   NUMBER(9) NOT NULL,
 	COMISION_PCT  NUMBER(3),
 	DEPT_NO   NUMBER(2) NOT NULL,
	CONSTRAINT EMPLE_PK PRIMARY KEY (EMP_NO),
	CONSTRAINT EMPLE_DIR_FK FOREIGN KEY (ID_JEFE)
				REFERENCES EMPLE(EMP_NO)  ON DELETE SET NULL,
	CONSTRAINT EMPLE_DEP_FK FOREIGN KEY (DEPT_NO)
				REFERENCES DEPART(DEPT_NO) ON DELETE CASCADE);

INSERT INTO EMPLE VALUES (7839,'REY','PRESIDENTE',NULL,TO_DATE('17/11/1981','DD/MM/YYYY'),6500,NULL,10);
INSERT INTO EMPLE VALUES (7566,'JIMENEZ','GERENTE',7839,TO_DATE('12/04/1981','DD/MM/YYYY'),3867,NULL,20);
INSERT INTO EMPLE VALUES (7698,'NEGRO','GERENTE',7839,TO_DATE('11/05/1981','DD/MM/YYYY'),3705,NULL,30);
INSERT INTO EMPLE VALUES (7782,'CEREZO','GERENTE',7839,TO_DATE('19/06/1981','DD/MM/YYYY'),3185,NULL,10);
INSERT INTO EMPLE VALUES (7788,'GIL','ANALISTA',7566,TO_DATE('19/11/1981','DD/MM/YYYY'),3900,NULL,20);
INSERT INTO EMPLE VALUES (7902,'FERNANDEZ','ANALISTA',7566,TO_DATE('13/12/1981','DD/MM/YYYY'),3900,NULL,20);
INSERT INTO EMPLE VALUES (7499,'ARROYO','COMERCIAL',7698,TO_DATE('20/02/1980','DD/MM/YYYY'),2080,10,30);
INSERT INTO EMPLE VALUES (7521,'SALA','COMERCIAL',7698,TO_DATE('22/02/1981','DD/MM/YYYY'),1625,5,30);
INSERT INTO EMPLE VALUES (7654,'MARTIN','COMERCIAL',7698,TO_DATE('29/09/1981','DD/MM/YYYY'),1625,5,30);
INSERT INTO EMPLE VALUES (7844,'TOVAR','COMERCIAL',7698,TO_DATE('18/09/1981','DD/MM/YYYY'),1950,8,30);
INSERT INTO EMPLE VALUES (7900,'JIMENO','PROGRAMADOR',7566,TO_DATE('13/12/1981','DD/MM/YYYY'),1235,NULL,30);
INSERT INTO EMPLE VALUES (7369,'SANCHEZ','PROGRAMADOR',7566,TO_DATE('17/12/1980','DD/MM/YYYY'),1040,NULL,20);
INSERT INTO EMPLE VALUES (7876,'ALONSO','PROGRAMADOR',7788,TO_DATE('23/09/1981','DD/MM/YYYY'),1430,NULL,20);
INSERT INTO EMPLE VALUES (7934,'SANCHEZ','AUXILIAR',7782,TO_DATE('23/01/1982','DD/MM/YYYY'),1690,NULL,10);

COMMIT;

--EJERCICIO 4
--TABLAS
SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME) IN ('DEPART','EMPLE');
--COLUMNAS
DESC EMPLE
DESC DEPART

--RESTRICCIONES
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE UPPER(TABLE_NAME) IN ('DEPART','EMPLE');

--COLUMNAS DE RESTRICCION
SELECT *
FROM USER_CONS_COLUMNS
WHERE UPPER(TABLE_NAME) IN ('DEPART','EMPLE');

--CONTENIDO DE LAS COLUMNAS
SELECT * FROM EMPLE;
SELECT * FROM DEPART;

--ESPECIALISTA A

--APARTADO-1
  SELECT salario, apellido, dept_no
  FROM emple
  WHERE salario > 2000 
  AND DEPT_NO IN(10,20);

--APARTADO-2
  SELECT salario, apellido
  FROM emple
  WHERE salario 
  BETWEEN 1500 AND 2000;
  
--APARTADO-3
  SELECT apellido
  FROM emple
  WHERE dept_no=30 OR dept_no=10;

--APARTADO-4
  SELECT apellido, oficio
  FROM emple
  WHERE id_jefe IS NULL;

--ESPECIALISTA B

  --APARTADO-1
    select * 
    from EMPLE 
    where APELLIDO 
    like 'J%';
  
  --APARTADO-2
    SELECT salario, apellido
    FROM emple
    WHERE salario 
    NOT BETWEEN 1500 AND 2000;
  
  --APARTADO-3
    SELECT apellido
    FROM emple
    WHERE DEPT_NO NOT IN (30,10);
  
  --APARTADO-4
  SELECT DISTINCT OFICIO
  FROM EMPLE;
--ESPECIALISTA C

    --APARTADO-1
      select * 
      from EMPLE 
      where APELLIDO 
      like '_R%';
    
    --APARTADO-2
      select APELLIDO 
      from EMPLE 
      where UPPER(OFICIO) = 'VENDEDOR' OR UPPER(OFICIO) = 'ANALISTA' OR UPPER(OFICIO) = 'EMPLEADO';
    
    --APARTADO-3
      select APELLIDO 
      from EMPLE 
      where COMISION_PCT IS NULL;
    
    --APARTADO-4
      select EMP_NO, APELLIDO,OFICIO,DEPT_NO 
      from EMPLE 
      where dept_no = 20 
      ORDER BY APELLIDO, SALARIO;


--ESPECIALISTA D
--EJERCICIO 5
--APARTADO 1
  SELECT APELLIDO 
  FROM EMPLE 
  WHERE APELLIDO LIKE 'A%O%'; 

--APARTADO 2
  SELECT APELLIDO 
  FROM EMPLE 
  WHERE UPPER(OFICIO) NOT IN ('VENDEDOR','ANALISTA','EMPLEADO');

--APARTADO 3
  SELECT APELLIDO 
  FROM EMPLE
  WHERE COMISION_PCT IS NOT NULL;

--APARTADO 4
  SELECT APELLIDO
  FROM EMPLE 
  WHERE UPPER(OFICIO) IN('ANALISTA')
  ORDER BY EMP_NO;



