set serveroutput on

-- Select 1 fila con Función de Grupo:

DECLARE
NUEVOLOC DEPART.LOC%TYPE:='VITORIA';
NUEVODEPART DEPART.DEPT_NO%TYPE:=90;
E_VACIO EXCEPTION;
LOC_MAX EXCEPTION;
V_ERROR VARCHAR2(250);
PRAGMA EXCEPTION_INIT(LOC_MAX,-12899);
BEGIN
UPDATE DEPART SET LOC=UPPER(NUEVOLOC) WHERE DEPT_NO=NUEVODEPART;
IF SQL%NOTFOUND THEN
  RAISE E_VACIO;
ELSE
dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' SE HA CAMBIADO A LA LOCALIDAD '||NUEVOLOC);
END IF;

EXCEPTION 
WHEN E_VACIO THEN 
  dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' NO EXISTE');
WHEN LOC_MAX THEN
  RAISE_APPLICATION_ERROR('-20001','LA LOCALIDAD TIENE DEMASIADOS CARACTERES');
WHEN VALUE_ERROR THEN
 dbms_output.put_line('VALOR ERRONEO');
WHEN OTHERS THEN
  V_ERROR:='Error Oracle: ' ||to_char(SQLCODE)||', '||SQLERRM;
  RAISE_APPLICATION_ERROR('-2000', V_ERROR);
END;



--NO ANONIMO (CON PARAMETROS EN VEZ DE VARIABLES)

/*LOS PARAMETRO SE TIENEN QUE SABER ANTES DE EJECUTAR EL
PROCEDIMIENTO

PARA EJECUTAR ES:
EXECUTE MODIFICAR_DEPART(LOCALIDAD,DEPARTAMENTO)*/

CREATE PROCEDURE MODIFICAR_DEPART

(NUEVOLOC DEPART.LOC%TYPE,
NUEVODEPART DEPART.DEPT_NO%TYPE)
IS
E_VACIO EXCEPTION;
LOC_MAX EXCEPTION;
V_ERROR VARCHAR2(250);
PRAGMA EXCEPTION_INIT(LOC_MAX,-12899);
BEGIN
UPDATE DEPART SET LOC=UPPER(NUEVOLOC) WHERE DEPT_NO=NUEVODEPART;
IF SQL%NOTFOUND THEN
  RAISE E_VACIO;
ELSE
dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' SE HA CAMBIADO A LA LOCALIDAD '||NUEVOLOC);
END IF;

EXCEPTION 
WHEN E_VACIO THEN 
  dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' NO EXISTE');
WHEN LOC_MAX THEN
  RAISE_APPLICATION_ERROR('-20001','LA LOCALIDAD TIENE DEMASIADOS CARACTERES');
WHEN VALUE_ERROR THEN
 dbms_output.put_line('VALOR ERRONEO');
WHEN OTHERS THEN
  V_ERROR:='Error Oracle: ' ||to_char(SQLCODE)||', '||SQLERRM;
  RAISE_APPLICATION_ERROR('-2000', V_ERROR);
END MODIFICAR_DEPART;

