set serveroutput on

-- Select 1 fila con Función de Grupo:

DECLARE
NUEVODEPART DEPART.DEPT_NO%TYPE:=50;
E_VACIO EXCEPTION;
V_ERROR VARCHAR2(250);
BEGIN
DELETE FROM DEPART WHERE DEPT_NO=NUEVODEPART;
IF SQL%NOTFOUND THEN
  RAISE E_VACIO;
ELSE
dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' SE HA BORRADO CON EXITO');
dbms_output.put_line(SQL%ROWCOUNT||' FILAS ELIMINADAS');
END IF;

EXCEPTION 
WHEN E_VACIO THEN 
  dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' NO EXISTE');
WHEN VALUE_ERROR THEN
 dbms_output.put_line('VALOR ERRONEO');
WHEN OTHERS THEN
  V_ERROR:='Error Oracle: ' ||to_char(SQLCODE)||', '||SQLERRM;
  RAISE_APPLICATION_ERROR('-2000', V_ERROR);
END;

--NO ANONIMO
CREATE PROCEDURE BORRAR_DEPART
IS
NUEVODEPART DEPART.DEPT_NO%TYPE:=50;
E_VACIO EXCEPTION;
V_ERROR VARCHAR2(250);
BEGIN
DELETE FROM DEPART WHERE DEPT_NO=NUEVODEPART;
IF SQL%NOTFOUND THEN
  RAISE E_VACIO;
ELSE
dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' SE HA BORRADO CON EXITO');
dbms_output.put_line(SQL%ROWCOUNT||' FILAS ELIMINADAS');
END IF;

EXCEPTION 
WHEN E_VACIO THEN 
  dbms_output.put_line('EL DEPARTAMENTO '||to_char(NUEVODEPART)||' NO EXISTE');
WHEN VALUE_ERROR THEN
 dbms_output.put_line('VALOR ERRONEO');
WHEN OTHERS THEN
  V_ERROR:='Error Oracle: ' ||to_char(SQLCODE)||', '||SQLERRM;
  RAISE_APPLICATION_ERROR('-2000', V_ERROR);
END BORRAR_DEPART;